export const booksConstants = {
    ZERO: 0,
    ONE: 1,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    FIVE: 5,
    BOOK_PRICE: 50,
    FIVE_PERCENT: 0.95,
    TEN_PERCENT: 0.9,
    TWENTY_PERCENT: 0.8,
    TWENTY_FIVE_PERCENT: 0.75,
    CLEN_CODE: 'cleanCode',
    THE_CLEAN_CODER: 'cleanCoder',
    CLEAN_ARCHITECTURE: 'cleanArchitecture',
    TEST_DRIVEN_DEVELOPMENT: 'tdd',
    LEGACY_CODE: 'legacyCode',
}
